# Generated by Django 2.1.1 on 2018-09-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activities_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='qrcode2',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='qrcode1',
        ),
    ]
