# Generated by Django 2.1.1 on 2018-10-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20180916_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='permitted',
            field=models.BooleanField(default=False),
        ),
    ]
