# Generated by Django 2.1.1 on 2018-10-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_groups_permitted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'ordering': ['-begin', '-pub_date'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
    ]
