# Generated by Django 2.1.1 on 2018-10-20 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20181020_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
