# Generated by Django 2.1.1 on 2018-10-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activities_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='logo',
            field=models.ImageField(default=0, upload_to='logo'),
            preserve_default=False,
        ),
    ]
