# Generated by Django 2.1.1 on 2018-10-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_groups_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='interval',
            field=models.BooleanField(default=False),
        ),
    ]
