# Generated by Django 2.1.1 on 2018-10-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_activities_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='showup',
            field=models.BooleanField(default=False),
        ),
    ]
